spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.106.6.230:3306/RealTourR8_QJ_B2B?characterEncoding=utf-8&allowMultiQueries=true
    username: realtour
    password: 333YCFXzyz!
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
  #  redis:
  #    host: 192.168.15.148
  #    port: 6379
  #    timeout: 300
  #    password: tepia
  #    database: 0
  #    pool:
  #      max-idle: 8
  #      min-idle: 10
  #      max-active: 100
  #      max-wait: -1
  rabbitmq:
    host: 39.106.6.230
    port: 5672
    username: realtour
    password: realtour
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml