spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.201.105:1521:HSST
    username: hsstdev
    password: hsst888
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  redis:
#    host: 192.168.15.148
#    port: 6379
#    timeout: 300
#    password: tepia
#    database: 0
#    pool:
#      max-idle: 8
#      min-idle: 10
#      max-active: 100
#      max-wait: -1

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml